### ISSUE TITLE
Exceptions after docker launch

### ISSUE THREAD

**Issue by sbonaime** [gaetancollaud/fablab-api#27]
Hi,

After docker launch, everything seems to going well but then I have exceptions and plugins shutting down
````
docker-compose pull
docker-compose up
Pulling mysql (mysql:5.7)...
5.7: Pulling from library/mysql
804555ee0376: Pull complete
c53bab458734: Pull complete
ca9d72777f90: Pull complete
2d7aad6cb96e: Pull complete
8d6ca35c7908: Pull complete
6ddae009e760: Pull complete
327ae67bbe7b: Pull complete
31f1f8385b27: Pull complete
a5a3ad97e819: Pull complete
48bede7828ac: Pull complete
380afa2e6973: Pull complete
Digest: sha256:b38555e593300df225daea22aeb104eed79fc80d2f064fde1e16e1804d00d0fc
Status: Downloaded newer image for mysql:5.7
Pulling web (gaetancollaud/fablab-manager:latest)...
latest: Pulling from gaetancollaud/fablab-manager
f7e2b70d04ae: Pull complete
05d40fc3cf34: Pull complete
b235bdb95dc9: Pull complete
9a9ecf5ba38f: Pull complete
e7cf7535df66: Pull complete
ada8ad4edf45: Pull complete
6e280536eb7d: Pull complete
85754676f67b: Pull complete
Digest: sha256:8b774de5bf7e977bbb977913fcf3ed82996b094f8b6764bd5c29930923c3d6f1
Status: Downloaded newer image for gaetancollaud/fablab-manager:latest
Creating fablabmanager_mysql_1 ... done
Creating fablabmanager_mysql_1 ...
Creating fablabmanager_web_1   ... done
Attaching to fablabmanager_mysql_1, fablabmanager_web_1
mysql_1  | 2020-01-02 14:31:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
mysql_1  | 2020-01-02 14:31:17+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1  | 2020-01-02 14:31:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
mysql_1  | 2020-01-02 14:31:17+00:00 [Note] [Entrypoint]: Initializing database files
mysql_1  | 2020-01-02T14:31:17.169169Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1  | 2020-01-02T14:31:17.449531Z 0 [Warning] InnoDB: New log files created, LSN=45790
mysql_1  | 2020-01-02T14:31:17.846994Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
mysql_1  | 2020-01-02T14:31:18.142123Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 89e4ee35-2d6c-11ea-8569-0242ac130002.
mysql_1  | 2020-01-02T14:31:18.144501Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
mysql_1  | 2020-01-02T14:31:18.745773Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1  | 2020-01-02T14:31:18.841894Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
web_1    | 14:31:19.476 [main] INFO  n.collaud.fablab.manager.Application - Starting Application v2.1.6 on 73b9f86ef714 with PID 1 (/app.jar started by root in /)
web_1    | 14:31:19.480 [main] INFO  n.collaud.fablab.manager.Application - No active profile set, falling back to default profiles: default
web_1    | 14:31:22.692 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
web_1    | 14:31:22.708 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
web_1    | 14:31:22.709 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.37
web_1    | 14:31:22.820 [localhost-startStop-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
mysql_1  | 2020-01-02 14:31:23+00:00 [Note] [Entrypoint]: Database files initialized
mysql_1  | 2020-01-02 14:31:23+00:00 [Note] [Entrypoint]: Starting temporary server
mysql_1  | 2020-01-02 14:31:23+00:00 [Note] [Entrypoint]: Waiting for server startup
mysql_1  | 2020-01-02T14:31:23.241392Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1  | 2020-01-02T14:31:23.243530Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 80 ...
mysql_1  | 2020-01-02T14:31:23.247256Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1  | 2020-01-02T14:31:23.247318Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1  | 2020-01-02T14:31:23.247356Z 0 [Note] InnoDB: Uses event mutexes
mysql_1  | 2020-01-02T14:31:23.247380Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1  | 2020-01-02T14:31:23.247409Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1  | 2020-01-02T14:31:23.247460Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1  | 2020-01-02T14:31:23.247857Z 0 [Note] InnoDB: Number of pools: 1
mysql_1  | 2020-01-02T14:31:23.248052Z 0 [Note] InnoDB: Not using CPU crc32 instructions
mysql_1  | 2020-01-02T14:31:23.250503Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_1  | 2020-01-02T14:31:23.261406Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1  | 2020-01-02T14:31:23.264417Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1  | 2020-01-02T14:31:23.276929Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1  | 2020-01-02T14:31:23.299560Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1  | 2020-01-02T14:31:23.299686Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1  | 2020-01-02T14:31:23.314462Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1  | 2020-01-02T14:31:23.315692Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1  | 2020-01-02T14:31:23.315768Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1  | 2020-01-02T14:31:23.316685Z 0 [Note] InnoDB: Waiting for purge to start
web_1    | 14:31:23.334 [main] INFO  o.f.c.internal.util.VersionPrinter - Flyway 4.0 by Boxfuse
mysql_1  | 2020-01-02T14:31:23.367164Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 2628227
mysql_1  | 2020-01-02T14:31:23.368144Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1  | 2020-01-02T14:31:23.379119Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1  | 2020-01-02T14:31:23.381280Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1  | 2020-01-02T14:31:23.381400Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
mysql_1  | 2020-01-02T14:31:23.382338Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1  | 2020-01-02T14:31:23.382492Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql_1  | 2020-01-02T14:31:23.383134Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200102 14:31:23
mysql_1  | 2020-01-02T14:31:23.389963Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1  | 2020-01-02T14:31:23.401886Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1  | 2020-01-02T14:31:23.402193Z 0 [Note] mysqld: ready for connections.
mysql_1  | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
mysql_1  | 2020-01-02 14:31:24+00:00 [Note] [Entrypoint]: Temporary server started.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql_1  | 2020-01-02 14:31:26+00:00 [Note] [Entrypoint]: Creating database fablab
mysql_1  | 2020-01-02 14:31:26+00:00 [Note] [Entrypoint]: Creating user fablab
mysql_1  | 2020-01-02 14:31:26+00:00 [Note] [Entrypoint]: Giving user fablab access to schema fablab
mysql_1  |
mysql_1  | 2020-01-02 14:31:26+00:00 [Note] [Entrypoint]: Stopping temporary server
mysql_1  | 2020-01-02T14:31:26.437169Z 0 [Note] Giving 0 client threads a chance to die gracefully
mysql_1  | 2020-01-02T14:31:26.437197Z 0 [Note] Shutting down slave threads
mysql_1  | 2020-01-02T14:31:26.437204Z 0 [Note] Forcefully disconnecting 0 remaining clients
mysql_1  | 2020-01-02T14:31:26.437210Z 0 [Note] Event Scheduler: Purging the queue. 0 events
mysql_1  | 2020-01-02T14:31:26.437259Z 0 [Note] Binlog end
mysql_1  | 2020-01-02T14:31:26.437985Z 0 [Note] Shutting down plugin 'ngram'
mysql_1  | 2020-01-02T14:31:26.437998Z 0 [Note] Shutting down plugin 'partition'
mysql_1  | 2020-01-02T14:31:26.438002Z 0 [Note] Shutting down plugin 'BLACKHOLE'
mysql_1  | 2020-01-02T14:31:26.438021Z 0 [Note] Shutting down plugin 'ARCHIVE'
mysql_1  | 2020-01-02T14:31:26.438025Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
mysql_1  | 2020-01-02T14:31:26.438071Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
mysql_1  | 2020-01-02T14:31:26.438075Z 0 [Note] Shutting down plugin 'MyISAM'
mysql_1  | 2020-01-02T14:31:26.438082Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
mysql_1  | 2020-01-02T14:31:26.438085Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
mysql_1  | 2020-01-02T14:31:26.438088Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
mysql_1  | 2020-01-02T14:31:26.438091Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
mysql_1  | 2020-01-02T14:31:26.438094Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
mysql_1  | 2020-01-02T14:31:26.438097Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
mysql_1  | 2020-01-02T14:31:26.438100Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
mysql_1  | 2020-01-02T14:31:26.438102Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
mysql_1  | 2020-01-02T14:31:26.438106Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
mysql_1  | 2020-01-02T14:31:26.438109Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
mysql_1  | 2020-01-02T14:31:26.438112Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
mysql_1  | 2020-01-02T14:31:26.438115Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
mysql_1  | 2020-01-02T14:31:26.438118Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
mysql_1  | 2020-01-02T14:31:26.438121Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
mysql_1  | 2020-01-02T14:31:26.438124Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
mysql_1  | 2020-01-02T14:31:26.438127Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
mysql_1  | 2020-01-02T14:31:26.438130Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
mysql_1  | 2020-01-02T14:31:26.438132Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
mysql_1  | 2020-01-02T14:31:26.438135Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
mysql_1  | 2020-01-02T14:31:26.438138Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
mysql_1  | 2020-01-02T14:31:26.438141Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
mysql_1  | 2020-01-02T14:31:26.438144Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
mysql_1  | 2020-01-02T14:31:26.438147Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
mysql_1  | 2020-01-02T14:31:26.438150Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
mysql_1  | 2020-01-02T14:31:26.438153Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
mysql_1  | 2020-01-02T14:31:26.438156Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
mysql_1  | 2020-01-02T14:31:26.438159Z 0 [Note] Shutting down plugin 'INNODB_CMP'
mysql_1  | 2020-01-02T14:31:26.438162Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
mysql_1  | 2020-01-02T14:31:26.438164Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
mysql_1  | 2020-01-02T14:31:26.438167Z 0 [Note] Shutting down plugin 'INNODB_TRX'
mysql_1  | 2020-01-02T14:31:26.438170Z 0 [Note] Shutting down plugin 'InnoDB'
mysql_1  | 2020-01-02T14:31:26.438230Z 0 [Note] InnoDB: FTS optimize thread exiting.
mysql_1  | 2020-01-02T14:31:26.438423Z 0 [Note] InnoDB: Starting shutdown...
mysql_1  | 2020-01-02T14:31:26.538836Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
mysql_1  | 2020-01-02T14:31:26.539115Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 200102 14:31:26

web_1    | 14:31:27.491 [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
web_1    | 14:31:27.494 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
web_1    | 14:31:27.519 [main] ERROR o.s.boot.SpringApplication - Application startup failed
web_1    | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
web_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1631)
web_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
web_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
web_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
web_1    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
web_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
web_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
web_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297)
web_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
web_1    | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080)
web_1    | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
web_1    | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
web_1    | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
web_1    | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
web_1    | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
web_1    | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
web_1    | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
web_1    | 	at net.collaud.fablab.manager.Application.main(Application.java:18)
web_1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
web_1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
web_1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
web_1    | 	at java.lang.reflect.Method.invoke(Method.java:498)
web_1    | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
web_1    | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
web_1    | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
web_1    | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
web_1    | Caused by: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
web_1    | 	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
web_1    | 	at org.flywaydb.core.Flyway.execute(Flyway.java:1314)
web_1    | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
web_1    | 	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
web_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1689)
web_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1627)
web_1    | 	... 25 common frames omitted
web_1    | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
web_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
web_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
web_1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
web_1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
web_1    | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
web_1    | 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
web_1    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
web_1    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
web_1    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
web_1    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
web_1    | 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
web_1    | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
web_1    | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
web_1    | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
web_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
web_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
web_1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
web_1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
web_1    | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
web_1    | 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
web_1    | 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
web_1    | 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
web_1    | 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
web_1    | 	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153)
web_1    | 	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144)
web_1    | 	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)
web_1    | 	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)
web_1    | 	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
web_1    | 	... 30 common frames omitted
web_1    | Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
web_1    |
web_1    | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
web_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
web_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
web_1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
web_1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
web_1    | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
web_1    | 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
web_1    | 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342)
web_1    | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197)
web_1    | 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
web_1    | 	... 47 common frames omitted
web_1    | Caused by: java.net.ConnectException: Connection refused (Connection refused)
web_1    | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
web_1    | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
web_1    | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
web_1    | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
web_1    | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
web_1    | 	at java.net.Socket.connect(Socket.java:589)
web_1    | 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
web_1    | 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301)
web_1    | 	... 49 common frames omitted
fablabmanager_web_1 exited with code 1

````

**Comment by gaetancollaud** [comment]
Hello,

The issue here is that mysql takes too long to start.

Try starting mysql and after a few second the fablab-manager.
